 const personsData = [

    { firstName:'Arnaldo', secondName:'Muñoz', lastName:'Pizarro', email:'arnaldo.ap.pizarro@bhpbilliton.com',  masterArea:'Water Supply'},
    { firstName:'Jose', secondName:'Pardo', lastName:'Pacheco', email:'jose.p.pacheco@bhpbilliton.com',  masterArea:'Water Supply'},
    { firstName:'Sandro', secondName:'Arancibia', lastName:'Bernal', email:'sandro.si.bernal@bhpbilliton.com',  masterArea:'Lifting Operations'},
    { firstName:'Pedro', secondName:'Rivera', lastName:'Cortes', email:'pedro.pm.cortes2@bhpbilliton.com',  masterArea:'Lifting Operations'},
    { firstName:'Jose', secondName:'Cid', lastName:'Gomez', email:'jose.e.gomez@bhpbilliton.com',  masterArea:'Lifting Operations'},
    { firstName:'Heraldo', secondName:'Bravo', lastName:'Arroyo', email:'heraldo.r.arroyo@bhpbilliton.com',  masterArea:'Lifting Operations'},
    { firstName:'Victor', secondName:'Pino', lastName:'Perez', email:'victor.vm.perez@bhpbilliton.com',  masterArea:'Lifting Operations'},
    { firstName:'Daysi', secondName:'Narvaez', lastName:'Monsalvez', email:'daysidd.monsalvez@bhpbilliton.com',  masterArea:'Water Supply'},
    { firstName:'Camila', secondName:'Apaza', lastName:'Escobar', email:'camila.escobar@bhpbilliton.com',  masterArea:'Water Supply'},
    { firstName:'Marcela', secondName:'Rivera', lastName:'Salazar', email:'marcela.salazar@bhpbilliton.com',  masterArea:'Water Supply'},
    { firstName:'Roxana', secondName:'Bugueño', lastName:'Latin', email:'roxana.latin@bhpbilliton.com',  masterArea:'Water Supply'},
    { firstName:'Sofia', secondName:'Velasquez', lastName:'Leiva', email:'sofia.leiva@bhpbilliton.com',  masterArea:'Water Supply'},
    { firstName:'Viviana', secondName:'Ballesteros', lastName:'Molina', email:'viviana.molina@bhpbilliton.com',  masterArea:'Water Supply'},
    { firstName:'Sonia', secondName:'Rojas', lastName:'Molina', email:'sonia.molina@bhpbilliton.com',  masterArea:'Water Supply'},
    { firstName:'Marcia', secondName:'Perez', lastName:'Lobos', email:'marciamd.lobos@bhpbilliton.com',  masterArea:'Water Supply'},
    { firstName:'Melissa', secondName:'Godoy', lastName:'Rivera', email:'melissa.rivera@bhpbilliton.com',  masterArea:'Water Supply'},
    { firstName:'Yusvana', secondName:'Gonzalez', lastName:'Jofre', email:'yusvana.jofre@bhpbilliton.com',  masterArea:'Water Supply'},
    { firstName:'Alejandro', secondName:'Rodriguez', lastName:'Rojas', email:'alejandro.l.rojas@bhpbilliton.com',  masterArea:'Water Supply'},
    { firstName:'Jose', secondName:'Cejas', lastName:'Cejas', email:'jose.l.cejas@bhpbilliton.com',  masterArea:'Water Supply'},
    { firstName:'Monica', secondName:'Valenzuela', lastName:'Orrego', email:'monica.mp.orrego@bhpbilliton.com',  masterArea:'Water Supply'},
    { firstName:'Arnaldo', secondName:'Araya', lastName:'Liquitay', email:'arnaldo.ag.liquitay@bhpbilliton.com',  masterArea:'Water Supply'},
    { firstName:'Marco', secondName:'Bermudez', lastName:'Rivera', email:'marco.a.rivera@bhpbilliton.com',  masterArea:'Water Supply'},
    { firstName:'Luis', secondName:'Castillo', lastName:'Perez', email:'luis.u.perez@bhpbilliton.com',  masterArea:'Water Supply'},
    { firstName:'Ricardo', secondName:'Herrera', lastName:'Romero', email:'ricardo.ra.romero@bhpbilliton.com',  masterArea:'Water Supply'},
    { firstName:'Audalio', secondName:'Rojas', lastName:'Toro', email:'audalio.ac.toro@bhpbilliton.com',  masterArea:'Water Supply'},
    { firstName:'Carlos', secondName:'Campos', lastName:'Soto', email:'carlos.cg.soto@bhpbilliton.com',  masterArea:'Water Supply'},
    { firstName:'Leonidas', secondName:'Bahamondes', lastName:'Psijas', email:'leonidas.lp.psijas@bhpbilliton.com',  masterArea:'Water Supply'},
    { firstName:'Guillermo', secondName:'Ramirez', lastName:'Apaz', email:'guillermo.gf.apaz@bhpbilliton.com',  masterArea:'Water Supply'},
    { firstName:'Hector', secondName:'Melendez', lastName:'Paez', email:'paez.g.hector@bhpbilliton.com',  masterArea:'Water Supply'},
    { firstName:'Henry', secondName:'Piñones', lastName:'Berenguela', email:'henry.hr.berenguela@bhpbilliton.com',  masterArea:'Water Supply'},
    { firstName:'Arturo', secondName:'Mejias', lastName:'Castro', email:'arturo.am.castro@bhpbilliton.com',  masterArea:'Water Supply'},
    { firstName:'Marcelo', secondName:'Velasquez', lastName:'Rodriguez', email:'ma@bhpbilliton.com',  masterArea:'Water Supply'},
    { firstName:'Rodrigo', secondName:'Castro', lastName:'Dominguez', email:'rodrigo.ra.dominguez@bhpbilliton.com',  masterArea:'Maintenance Water'},
    { firstName:'Pablo', secondName:'Jimenez', lastName:'Torres', email:'pablo.pa.torres@bhpbilliton.com',  masterArea:'Maintenance Overhead Cranes'},
    { firstName:'Ruben', secondName:'Diaz', lastName:'Salinas', email:'ruben.c.salinas@bhpbilliton.com',  masterArea:'Maintenance Overhead Cranes'},
    { firstName:'Jose', secondName:'Flandez', lastName:'Mancilla', email:'josejl.mancilla@bhpbilliton.com',  masterArea:'Maintenance Water'},
    { firstName:'Alejandra', secondName:'Olguin', lastName:'Cortes', email:'alejandra.cortes@bhpbilliton.com',  masterArea:'Maintenance Water'},
    { firstName:'Jonathan', secondName:'Vasquez', lastName:'Alarcon', email:'jonathan.alarcon@bhpbilliton.com',  masterArea:'Maintenance Water'},
    { firstName:'Gladys', secondName:'Maldini', lastName:'Guevara', email:'gladys.guevera@bhpbilliton.com',  masterArea:'Maintenance Water'},
    { firstName:'Paula', secondName:'Ramirez', lastName:'Araya', email:'paula.araya@bhpbilliton.com',  masterArea:'Maintenance Water'},
    { firstName:'Leandro', secondName:'Villalobos', lastName:'Arancibia', email:'leandro.m.arancibia@bhpbilliton.com',  masterArea:'Maintenance Water'},
    { firstName:'Christian', secondName:'Gordon', lastName:'Bugueño', email:'christian.cf.bugueno@bhpbilliton.com',  masterArea:'Maintenance Water'},
    { firstName:'Francisco', secondName:'Ruiz', lastName:'Cuadra', email:'francisco.fa.cuadra@bhpbilliton.com',  masterArea:'Maintenance Execution CHO'},
    { firstName:'Max', secondName:'Arancibia', lastName:'Rivera', email:'max.e.rivera@bhpbilliton.com',  masterArea:'Maintenance Execution CHO'},
    { firstName:'Rodolfo', secondName:'Cortes', lastName:'Rivera', email:'rodolfo.rr.rivera@bhpbilliton.com',  masterArea:'Maintenance Water'},
    { firstName:'Cristian', secondName:'Plaza', lastName:'Cortes', email:'cristian.cr.cortes@bhpbilliton.com',  masterArea:'Maintenance Water'},
    { firstName:'Jose', secondName:'Fuentes', lastName:'Muñoz', email:'jose.ja.munoz2@bhpbilliton.com',  masterArea:'Maintenance Overhead Cranes'},
    { firstName:'Roberto', secondName:'Cortes', lastName:'Morgado', email:'roberto.ra.morgado@bhpbilliton.com',  masterArea:'Maintenance Execution CHO'},
    { firstName:'Jose', secondName:'Rojas', lastName:'Diaz', email:'jose.jr.diaz@bhpbilliton.com',  masterArea:'Maintenance Execution CHO'},
    { firstName:'Guido', secondName:'Cisternas', lastName:'Gallegos', email:'gallegos.ga.guido@bhpbilliton.com',  masterArea:'Maintenance Water'},
    { firstName:'Carlos', secondName:'Palza', lastName:'Alfaro', email:'carlos.ch.alfaro@bhpbilliton.com',  masterArea:'Maintenance Overhead Cranes'},
    { firstName:'Gino', secondName:'Rojas', lastName:'Ramirez', email:'gino.gh.ramirez@bhpbilliton.com',  masterArea:'Maintenance Water'},
    { firstName:'Alejandro', secondName:'Monroy', lastName:'Riquelme', email:'alejandro.ao.riquelme@bhpbilliton.com',  masterArea:'Maintenance Execution CHO'},
    { firstName:'Felipe', secondName:'Godoy', lastName:'Castillo', email:'felipe.fp.castillo@bhpbilliton.com',  masterArea:'Maintenance Execution CHO'},
    { firstName:'Carlos', secondName:'Fuentes', lastName:'Sanchez', email:'carlos.cc.sanchez@bhpbilliton.com',  masterArea:'Maintenance Overhead Cranes'},
    { firstName:'Saul', secondName:'Aguilera', lastName:'Zambra', email:'saul.sf.zambra@bhpbilliton.com',  masterArea:'Maintenance Overhead Cranes'},
    { firstName:'Mauricio', secondName:'Hidalgo', lastName:'Nuñez', email:'mauricio.mj.nunez@bhpbilliton.com',  masterArea:'Maintenance Water'},
    { firstName:'Adrian', secondName:'Flores', lastName:'Palma', email:'adrian.palma@bhpbilliton.com',  masterArea:'Maintenance Water'},
    { firstName:'Maximiliano', secondName:'Lopez', lastName:'Quezada', email:'maximiliano.quezada@bhpbilliton.com',  masterArea:'Maintenance Water'},
    { firstName:'Milenko', secondName:'Torres', lastName:'Peña', email:'milenko.m.pena@bhpbilliton.com',  masterArea:'Maintenance Water'},
    { firstName:'Juan', secondName:'Arancibia', lastName:'Rivera', email:'juan.a.rivera@bhpbilliton.com',  masterArea:'Maintenance Water'},
    { firstName:'Jose', secondName:'Contardo', lastName:'Escobar', email:'jose.o.escobar@bhpbilliton.com',  masterArea:'Maintenance Overhead Cranes'},
    { firstName:'Gustavo', secondName:'Rodriguez', lastName:'Tapia', email:'gustavo.ge.tapia@bhpbilliton.com',  masterArea:'Maintenance Water'},
    { firstName:'Andres', secondName:'Saavedra', lastName:'Saavedra', email:'andres.m.saavedra@bhpbilliton.com',  masterArea:'Maintenance Water'},
    { firstName:'Manuel', secondName:'Serrano', lastName:'Tirado', email:'manuel.e.tirado@bhpbilliton.com',  masterArea:'Maintenance Overhead Cranes'},
    { firstName:'Cristian', secondName:'Salamanca', lastName:'Calderon', email:'ca@bhpbilliton.com',  masterArea:'Maintenance Water'},
    { firstName:'Darwin', secondName:'Monardez', lastName:'Pizarro', email:'darwin.h.pizarro@bhpbilliton.com',  masterArea:'Maintenance Overhead Cranes'},
    { firstName:'Luis', secondName:'Sanchez', lastName:'Villalobos', email:'luis.lh.villalobos@bhpbilliton.com',  masterArea:'A&I CHO'},
    { firstName:'Ricardo', secondName:'Cuevas', lastName:'Alfaro', email:'ricardo.ra.alfaro@bhpbilliton.com',  masterArea:'A&I CHO'},
    { firstName:'Luis', secondName:'Vallejos', lastName:'Fuenzalida', email:'luis.la.fuenzalida@bhpbilliton.com',  masterArea:'A&I CHO'},
    { firstName:'Andres', secondName:'Saka', lastName:'Montilla', email:'andres.ae.montilla@bhpbilliton.com',  masterArea:'A&I CHO'},
    { firstName:'Paloma', secondName:'Rodriguez', lastName:'Hurtado', email:'paloma.hurtado@bhpbilliton.com',  masterArea:'A&I CHO'},
    { firstName:'Marco', secondName:'Alvarez', lastName:'Sanchez', email:'marco.ms.sanchez@bhpbilliton.com',  masterArea:'A&I NPI'},
    { firstName:'Mauro', secondName:'Bruna', lastName:'Bull', email:'mauro.ma.bull@bhpbilliton.com',  masterArea:'A&I NPI'},
    { firstName:'Daniel', secondName:'Olguin', lastName:'Jerez', email:'daniel.dg.jerez@bhpbilliton.com',  masterArea:'A&I NPI'},
    { firstName:'Claudia', secondName:'Fuentes', lastName:'Rodriguez', email:'claudia.rodriguez@bhpbilliton.com',  masterArea:'A&I NPI'},
    { firstName:'Silvano', secondName:'Rojas', lastName:'Diaz', email:'silvano.a.diaz@bhpbilliton.com',  masterArea:'Personnel Serv Contract Management'},
    { firstName:'Armando', secondName:'Fajardo', lastName:'Godoy', email:'armando.aa.godoy@bhpbilliton.com',  masterArea:'Production Contract Management NPI'},
    { firstName:'Wido', secondName:'Bradanovich', lastName:'Pinto', email:'wido.wr.pinto@bhpbilliton.com',  masterArea:'Personnel Serv Contract Management'},
    { firstName:'Ariel', secondName:'Sobarzo', lastName:'Leal', email:'ariel.ac.leal@bhpbilliton.com',  masterArea:'Power Supply'},
    { firstName:'Cristian', secondName:'Conejeros', lastName:'Thenoux', email:'cristian.cm.thenoux@bhpbilliton.com',  masterArea:'Production Contract Management NPI'},
    { firstName:'German', secondName:'Torres', lastName:'Reyes', email:'german.ge.reyes@bhpbilliton.com',  masterArea:'Production Contract Management NPI'},
    { firstName:'Claudio', secondName:'Villa', lastName:'Hinojosa', email:'claudio.ch.hinojosa@bhpbilliton.com',  masterArea:'Personnel Serv Contract Management'},
    { firstName:'Pedro', secondName:'Araya', lastName:'Torres', email:'pedro.pa.torres91@bhpbilliton.com',  masterArea:'Production Contract Management NPI'},
    { firstName:'Gabriel', secondName:'Krumenacker', lastName:'Depallens', email:'gabriel.gi.depallens@bhpbilliton.com',  masterArea:'Personnel Serv Contract Management'},
    { firstName:'Brian', secondName:'Villarroel', lastName:'Aliaga', email:'brian.ba.aliaga@bhpbilliton.com',  masterArea:'Production Contract Management NPI'},
    { firstName:'Sergio', secondName:'Rehbein', lastName:'Avalos', email:'sergio.sg.avalos@bhpbilliton.com',  masterArea:'Production Contract Management NPI'},
    { firstName:'Cristian', secondName:'Retamal', lastName:'Bujes', email:'cristian.ca.bujes@bhpbilliton.com',  masterArea:'Production Contract Management NPI'},
    { firstName:'Paulina', secondName:'Osorio', lastName:'Rojas', email:'paulina.rojas@bhpbilliton.com',  masterArea:'Production Contract Management NPI'},
    { firstName:'Franco', secondName:'Pelech', lastName:'Mangili', email:'franco.fm.mangili@bhpbilliton.com',  masterArea:'Water Supply'},
    { firstName:'Aldo', secondName:'Tapia', lastName:'Galleguillos', email:'aldo.ar.galleguillos@bhpbilliton.com',  masterArea:'Production Pipeline & Filter'},
    { firstName:'Enzo', secondName:'Labbe', lastName:'Lopez', email:'enzo.ea.lopez@bhpbilliton.com',  masterArea:'Water Supply'},
    { firstName:'Osman', secondName:'Moya', lastName:'Duarte', email:'osman.or.duarte@bhpbilliton.com',  masterArea:'Maintenance Power'},
    { firstName:'Daniel', secondName:'Godoy', lastName:'Huerta', email:'daniel.d.huerta@bhpbilliton.com',  masterArea:'Maintenance Power'},
    { firstName:'Rodrigo', secondName:'Lizama', lastName:'Rojas', email:'rodrigo.ri.rojas@bhpbilliton.com',  masterArea:'Maintenance Power'},
    { firstName:'Ricardo', secondName:'Baracat', lastName:'Leiva', email:'ricardo.rm.leiva@bhpbilliton.com',  masterArea:'Maintenance Power'},
    { firstName:'Ignacio', secondName:'Aravena', lastName:'Ortiz', email:'ignacio.ia.ortiz@bhpbilliton.com',  masterArea:'Maintenance Power'},
    { firstName:'Gabriel', secondName:'Carneiro', lastName:'Iturra', email:'gabriel.iturra@bhpbilliton.com',  masterArea:'Maintenance Power'},
    { firstName:'Claudio', secondName:'Araya', lastName:'Gonzalez', email:'claudio.ca.gonzalez2@bhpbilliton.com',  masterArea:'Production Pipeline & Filter'},
    { firstName:'Carol', secondName:'Cancino', lastName:'Espejo', email:'carol.ca.espejo@bhpbilliton.com',  masterArea:'Prod. Planning'},
    { firstName:'Pedro', secondName:'Romero', lastName:'Cortes', email:'pedro.pj.cortes@bhpbilliton.com',  masterArea:'Ingenieria'},
    { firstName:'Claudio', secondName:'Quezada', lastName:'Vasquez', email:'claudio.cj.vasquez@bhpbilliton.com',  masterArea:'Ingenieria'},
    { firstName:'Abdon', secondName:'Antil', lastName:'Figueroa', email:'abdon.ae.figueroa@bhpbilliton.com',  masterArea:'Ingenieria'},
    { firstName:'Rodrigo', secondName:'Cortes', lastName:'Perez', email:'rodrigo.ra.perez2@bhpbilliton.com',  masterArea:'Ingenieria'},
    { firstName:'Rodrigo', secondName:'Rojas', lastName:'Valencia', email:'rodrigo.r.valencia@bhpbilliton.com',  masterArea:'Ingenieria'},
    { firstName:'Jorge', secondName:'Peñaloza', lastName:'Carrasco', email:'jorge.jb.carrasco@bhpbilliton.com',  masterArea:'Ingenieria'},
    { firstName:'Francisca', secondName:'Henriquez', lastName:'Labarca', email:'francisca.labarca@bhpbilliton.com',  masterArea:'Ingenieria'},
    { firstName:'Hector', secondName:'Moreno', lastName:'Herrera', email:'hector.a.herrera@bhpbilliton.com',  masterArea:'Power Supply'},
    { firstName:'Rodrigo', secondName:'Carrasco', lastName:'Rivas', email:'rodrigo.r.rivas@bhpbilliton.com',  masterArea:'Power Supply'},
    { firstName:'Edu', secondName:'Duran', lastName:'Brizuela', email:'edu.eh.brizuela@bhpbilliton.com',  masterArea:'Power Supply'},
    { firstName:'Amador', secondName:'Vidal', lastName:'Arriagada', email:'amador.am.arriagada@bhpbilliton.com',  masterArea:'Power Supply'},
    { firstName:'Priscilla', secondName:'Perez', lastName:'Alvarado', email:'priscilla.pj.alvarado@bhpbilliton.com',  masterArea:'Power Supply'},
    { firstName:'Karina', secondName:'Vergara', lastName:'Medina', email:'karina.medina@bhpbilliton.com',  masterArea:'Power Supply'},
    { firstName:'Juan', secondName:'Pereira', lastName:'Bugueño', email:'juan.a.bugueno@bhpbilliton.com',  masterArea:'Planning CHO'},
    { firstName:'Paula', secondName:'Flores', lastName:'Aranda', email:'paula.pl.aranda@bhpbilliton.com',  masterArea:'Prod. Planning'},
    { firstName:'Rosa', secondName:'Alar', lastName:'Araya', email:'rosa.rm.araya@bhpbilliton.com',  masterArea:'Planning CHO'},
    { firstName:'Rodrigo', secondName:'Aravena', lastName:'Aravena', email:'rodrigo.ra.aravena@bhpbilliton.com',  masterArea:'Prod. Planning'},
    { firstName:'Francisca', secondName:'Cuevas', lastName:'Jorquera', email:'francisca.jorquera@bhpbilliton.com',  masterArea:'Prod. Planning'},
    { firstName:'Poo             ', secondName:'Alan               ', lastName:'Cleveland           ', email:'brian.cleveland@bhpbilliton.com           ',  masterArea:'Maintenance Execution CHO'},
    { firstName:'Nancy', secondName:'Ayavire', lastName:'Quispe', email:'nancy.nm.quispe@bhpbilliton.com',  masterArea:'Prod. Planning'},
    { firstName:'Paulo', secondName:'Cuenca', lastName:'Trujillo', email:'paulo.pc.trujillo@bhpbilliton.com',  masterArea:'Power Supply'},
    { firstName:'Karen', secondName:'Villablanca', lastName:'Toro', email:'karen.ke.toro@bhpbilliton.com',  masterArea:'Prod. Planning'},
    { firstName:'Maria', secondName:'Maltes', lastName:'Zamora', email:'maria.ml.zamora@bhpbilliton.com',  masterArea:'Prod. Planning'},
    { firstName:'Niky', secondName:'Nuñez', lastName:'Triantafilo', email:'niky.ne.triantafilo@bhpbilliton.com',  masterArea:'Personnel Serv Contract Management'},
    { firstName:'Katherine', secondName:'Aravena', lastName:'Morales', email:'katherine.kk.morales@bhpbilliton.com',  masterArea:'Asistente'},
    { firstName:'Ramon', secondName:'Baeza', lastName:'Cifuentes', email:'ramon.a.cifuentes@bhpbilliton.com',  masterArea:'Gerencia General'},
    { firstName:'Rafael', secondName:'Arancibia', lastName:'Arancibia', email:'rafael.g.arancibia@bhpbilliton.com',  masterArea:'Maintenance Overhead Cranes'},
    { firstName:'Luis', secondName:'Santelices', lastName:'Salazar', email:'luis.a.salazar@bhpbilliton.com',  masterArea:'Maintenance Overhead Cranes'},
    { firstName:'Roberto', secondName:'Marin', lastName:'Alvarez', email:'roberto.r.alvarez@bhpbilliton.com',  masterArea:'Personnel Services'},
    { firstName:'Carolina', secondName:'Herrera', lastName:'Castillo', email:'carolina.ca.castillo@bhpbilliton.com',  masterArea:'Services Antofagasta'},
    { firstName:'Girlen', secondName:'Cisternas', lastName:'Viñales', email:'girlen.vinales@bhpbilliton.com',  masterArea:'Maintenance Water'},
    { firstName:'Claudia', secondName:'Guerrero', lastName:'Caceres', email:'claudia.caceres@bhpbilliton.com',  masterArea:'Maintenance Overhead Cranes'},
    { firstName:'Nydia', secondName:'Burboa', lastName:'Guzman', email:'nydia.guzman@bhpbilliton.com',  masterArea:'Maintenance Overhead Cranes'},
    { firstName:'Marisol', secondName:'Colque', lastName:'Soza', email:'marisol.soza@bhpbilliton.com',  masterArea:'Maintenance Overhead Cranes'},
    { firstName:'Johanna', secondName:'Reyes', lastName:'Arriagada', email:'johana.arriagada@bhpbilliton.com',  masterArea:'Maintenance Overhead Cranes'},
    { firstName:'Nicole', secondName:'Villarroel', lastName:'Videla', email:'nicole.videla@bhpbilliton.com',  masterArea:'Maintenance Execution CHO'},
    { firstName:'Angela', secondName:'Campusano', lastName:'Farias', email:'angela.farias@bhpbilliton.com',  masterArea:'Maintenance Execution CHO'},
    { firstName:'Juan', secondName:'Abarca', lastName:'Reinaga', email:'juan.a.reinaga@bhpbilliton.com',  masterArea:'CHO Mtto'},
    { firstName:'Juan', secondName:'Cofre', lastName:'Albarran', email:'juancarlos.albarran@bhpbilliton.com',  masterArea:'NPI Mtto'},
    { firstName:'Mario', secondName:'Palacios', lastName:'Uribe', email:'mario.mc.uribe@bhpbilliton.com',  masterArea:'SSPP'},
    { firstName:'Hector', secondName:'Santibañez', lastName:'Silva', email:'hector.m.silva@bhpbilliton.com',  masterArea:'NPI Prod'},
    { firstName:'Julian', secondName:'Ormeño', lastName:'Mansilla', email:'julian.je.mansilla@bhpbilliton.com',  masterArea:'CHO Prod'},
    { firstName:'Rodrigo', secondName:'Portilla', lastName:'Plaza', email:'rodrigo.ra.plaza2@bhpbilliton.com',  masterArea:'Management Comissioning'},
    { firstName:'Cristhian', secondName:'Gomez', lastName:'Bravo', email:'cristhian.ca.bravo@bhpbilliton.com',  masterArea:'Maintenance Execution CHO'},
    { firstName:'Mauricio', secondName:'Flores', lastName:'Lastra', email:'mauricio.a.lastra@bhpbilliton.com',  masterArea:'Maintenance Execution CHO'},
    { firstName:'Guillermo', secondName:'Toro', lastName:'Ogalde', email:'guillermo.t.ogalde@bhpbilliton.com',  masterArea:'Maintenance Overhead Cranes'},
    { firstName:'Mauricio', secondName:'Aravena', lastName:'Rauque', email:'mauricio.i.rauque@bhpbilliton.com',  masterArea:'Maintenance Overhead Cranes'},
    { firstName:'Lorenzo', secondName:'Flores', lastName:'Rivero', email:'lorenzo.ll.rivero@bhpbilliton.com',  masterArea:'Maintenance Overhead Cranes'},
    { firstName:'Alejandro', secondName:'Cousinard', lastName:'Barrios', email:'alejandro.ad.barrios@bhpbilliton.com',  masterArea:'Maintenance Execution CHO'},
    { firstName:'Jose', secondName:'Alvarez', lastName:'Arenas', email:'jose.arenas@bhpbilliton.com',  masterArea:'Maintenance Execution CHO'},
    { firstName:'Enrique', secondName:'Ordenes', lastName:'Gutierrez', email:'enrique.n.gutierrez@bhpbilliton.com',  masterArea:'Maintenance Execution CHO'},
    { firstName:'Fernando', secondName:'Huidobro', lastName:'Villalobos', email:'fernando.p.villalobos@bhpbilliton.com',  masterArea:'Maintenance Execution CHO'},
    { firstName:'Nestor', secondName:'Gonzalez', lastName:'Aguilera', email:'nestor.aguilera@bhpbilliton.com',  masterArea:'Maintenance Overhead Cranes'},
    { firstName:'Ricardo', secondName:'Gonzalez', lastName:'Jara', email:'ricardo.re.jara@bhpbilliton.com',  masterArea:'Maintenance Overhead Cranes'},
    { firstName:'Hernan', secondName:'Gonzalez', lastName:'Berrios', email:'hernan.p.berrios@bhpbilliton.com',  masterArea:'Maintenance Overhead Cranes'},
    { firstName:'Hector', secondName:'Gonzalez', lastName:'Castro', email:'hector.r.castro@bhpbilliton.com',  masterArea:'Maintenance Execution CHO'},
    { firstName:'Ramon', secondName:'Pozo', lastName:'Ramirez', email:'ramon.a.ramirez@bhpbilliton.com',  masterArea:'Maintenance Overhead Cranes'},
    { firstName:'Adolfo', secondName:'Araya', lastName:'Gonzalez', email:'adolfo.a.gonzalez@bhpbilliton.com',  masterArea:'Maintenance Execution CHO'},
    { firstName:'Karen', secondName:'Donoso', lastName:'Carrizo', email:'karen.carrizo@bhpbilliton.com',  masterArea:'Wells Field & Tailings Dam'},
    { firstName:'Leslie', secondName:'Salva', lastName:'Espindola', email:'leslie.espindola@bhpbilliton.com',  masterArea:'Production Port'},
    { firstName:'Camilo', secondName:'Bravo', lastName:'Garay', email:'camilo.ca.garay@bhpbilliton.com',  masterArea:'Maintenance Planning NPI'},
    { firstName:'Laura', secondName:'Gonzalez', lastName:'Suarez', email:'laura.suarez@bhpbilliton.com',  masterArea:'Maintenance Planning NPI'},
    { firstName:'Nelson', secondName:'Severino', lastName:'Oyarce', email:'nelson.oyarce@bhpbilliton.com',  masterArea:'Planning CHO'},
    { firstName:'Gonzalo', secondName:'Aguila', lastName:'Cabrera', email:'gonzalo.a.cabrera@bhpbilliton.com',  masterArea:'Planning CHO'},
    { firstName:'Lorenzo', secondName:'Campos', lastName:'Luengo', email:'lorenzo.la.luengo@bhpbilliton.com',  masterArea:'Planning CHO'},
    { firstName:'Sergio', secondName:'Salazar', lastName:'Olivares', email:'sergio.sa.olivares@bhpbilliton.com',  masterArea:'Maintenance Planning NPI'},
    { firstName:'Manuel', secondName:'Picon', lastName:'Aguirre', email:'manuel.ma.aguirre@bhpbilliton.com',  masterArea:'Maintenance Planning NPI'},
    { firstName:'Mario', secondName:'Soto', lastName:'Sanchez', email:'mario.mj.sanchez@bhpbilliton.com',  masterArea:'Maintenance Planning NPI'},
    { firstName:'Adolfo', secondName:'Cuadra', lastName:'Roldan', email:'adolfo.r.roldan@bhpbilliton.com',  masterArea:'Maintenance Planning NPI'},
    { firstName:'Ruperto', secondName:'Rosales', lastName:'Garrido', email:'ruperto.ra.garrido@bhpbilliton.com',  masterArea:'Production Pipeline & Filter'},
    { firstName:'Scarlett', secondName:'Cordova', lastName:'Vargas', email:'scarlett.vargas@bhpbilliton.com',  masterArea:'Production Pipeline & Filter'},
    { firstName:'Yury', secondName:'Quiñones', lastName:'Cuevas', email:'yuri.u.cuevas@bhpbilliton.com',  masterArea:'Production Pipeline & Filter'},
    { firstName:'Camilo', secondName:'Rivera', lastName:'Matsubara', email:'camilo.h.matsubara@bhpbilliton.com',  masterArea:'Wells Field & Tailings Dam'},
    { firstName:'Roberto', secondName:'Rojas', lastName:'Guerra', email:'roberto.ra.guerra@bhpbilliton.com',  masterArea:'Production Pipeline & Filter'},
    { firstName:'Julio', secondName:'Rozas', lastName:'Ramirez', email:'julio.jr.ramirez@bhpbilliton.com',  masterArea:'Production Pipeline & Filter'},
    { firstName:'Maycol', secondName:'Ponce', lastName:'Morales', email:'maycol.mn.morales@bhpbilliton.com',  masterArea:'Production Pipeline & Filter'},
    { firstName:'Claudio', secondName:'Jofre', lastName:'Perez', email:'claudio.ce.perez@bhpbilliton.com',  masterArea:'Production Pipeline & Filter'},
    { firstName:'Gerardo', secondName:'Castillo', lastName:'Gonzalez', email:'gerardo.ga.gonzalez@bhpbilliton.com',  masterArea:'Production Pipeline & Filter'},
    { firstName:'Rosa', secondName:'Gallardo', lastName:'Alfaro', email:'rosa.rt.alfaro@bhpbilliton.com',  masterArea:'Production Pipeline & Filter'},
    { firstName:'Gheraldy', secondName:'Saavedra', lastName:'Farias', email:'gheraldy.gc.farias@bhpbilliton.com',  masterArea:'Production Pipeline & Filter'},
    { firstName:'Julio', secondName:'Galleguillos', lastName:'Juarez', email:'julio.jj.juarez@bhpbilliton.com',  masterArea:'Production Pipeline & Filter'},
    { firstName:'Itzamar', secondName:'Menay', lastName:'Licuime', email:'itzamar.ia.licuime@bhpbilliton.com',  masterArea:'Production Pipeline & Filter'},
    { firstName:'Alexis', secondName:'Soza', lastName:'Soza', email:'alexis.am.soza@bhpbilliton.com',  masterArea:'Production Pipeline & Filter'},
    { firstName:'Roberto', secondName:'Echeverria', lastName:'Varela', email:'roberto.ra.varela@bhpbilliton.com',  masterArea:'Production Pipeline & Filter'},
    { firstName:'Abel', secondName:'Olivares', lastName:'Guerra', email:'abel.ag.guerra@bhpbilliton.com',  masterArea:'Production Pipeline & Filter'},
    { firstName:'Jesus', secondName:'Carvajal', lastName:'Iglesias', email:'jesus.je.iglesias@bhpbilliton.com',  masterArea:'Production Pipeline & Filter'},
    { firstName:'Mario', secondName:'Moya', lastName:'Ledezma', email:'mario.mh.ledezma@bhpbilliton.com',  masterArea:'Water Supply'},
    { firstName:'Pedro', secondName:'Mansilla', lastName:'Marin', email:'pedro.pd.marin@bhpbilliton.com',  masterArea:'Production Pipeline & Filter'},
    { firstName:'Javier', secondName:'Lamas', lastName:'Monsalve', email:'javier.jv.monsalve@bhpbilliton.com',  masterArea:'Production Pipeline & Filter'},
    { firstName:'Miguel', secondName:'Suazo', lastName:'Lopez', email:'miguel.ma.lopez@bhpbilliton.com',  masterArea:'Production Pipeline & Filter'},
    { firstName:'Vicente', secondName:'Flores', lastName:'Piñones', email:'vicente.ve.pinones@bhpbilliton.com',  masterArea:'Production Pipeline & Filter'},
    { firstName:'Sergio', secondName:'Mandiola', lastName:'Duran', email:'sergio.sp.duran@bhpbilliton.com',  masterArea:'Production Pipeline & Filter'},
    { firstName:'Antonio', secondName:'Castro', lastName:'Gallegos', email:'antonio.aa.gallegos@bhpbilliton.com',  masterArea:'Production Pipeline & Filter'},
    { firstName:'Juan', secondName:'Collao', lastName:'Rojas', email:'juan.jc.rojas2@bhpbilliton.com',  masterArea:'Production Pipeline & Filter'},
    { firstName:'Jorge', secondName:'Nuñez', lastName:'Villalon', email:'jorge.o.villalon@bhpbilliton.com',  masterArea:'Production Pipeline & Filter'},
    { firstName:'Agusto', secondName:'Gallardo', lastName:'Riveros', email:'augusto.al.riveros@bhpbilliton.com',  masterArea:'Production Pipeline & Filter'},
    { firstName:'Juan', secondName:'Villalobos', lastName:'Riveros', email:'juan.j.riveros@bhpbilliton.com',  masterArea:'Production Pipeline & Filter'},
    { firstName:'Raimundo', secondName:'Pacheco', lastName:'Estay', email:'raimundo.a.estay@bhpbilliton.com',  masterArea:'Production Pipeline & Filter'},
    { firstName:'Ruben', secondName:'Yañez', lastName:'Acosta', email:'ruben.e.acosta@bhpbilliton.com',  masterArea:'Production Pipeline & Filter'},
    { firstName:'Juan', secondName:'Zepeda', lastName:'Castañeda', email:'juan.i.castaneda@bhpbilliton.com',  masterArea:'Production Pipeline & Filter'},
    { firstName:'Alexis', secondName:'Diaz', lastName:'Cisternas', email:'alexis.j.cisternas@bhpbilliton.com',  masterArea:'Production Pipeline & Filter'},
    { firstName:'Pedro', secondName:'Vargas', lastName:'Jorquera', email:'pedro.e.jorquera@bhpbilliton.com',  masterArea:'Production Pipeline & Filter'},
    { firstName:'Jose', secondName:'Vega', lastName:'Martinez', email:'jose.m.martinez@bhpbilliton.com',  masterArea:'Production Pipeline & Filter'},
    { firstName:'Daniel', secondName:'Peña', lastName:'Contreras', email:'daniel.a.contreras@bhpbilliton.com',  masterArea:'Production Port'},
    { firstName:'Gabriel', secondName:'Zepeda', lastName:'Beltran', email:'gabriel.gs.beltran@bhpbilliton.com',  masterArea:'Production Pipeline & Filter'},
    { firstName:'Jessica', secondName:'Bozo', lastName:'Morales', email:'jessica.morales@bhpbilliton.com',  masterArea:'Production Port'},
    { firstName:'Juan', secondName:'Pasten', lastName:'Pedamonte', email:'juan.e.pedamonte@bhpbilliton.com',  masterArea:'Production Port'},
    { firstName:'Sergio', secondName:'Barrios', lastName:'Marin', email:'sergio.so.marin@bhpbilliton.com',  masterArea:'Production Port'},
    { firstName:'Patricio', secondName:'Campos', lastName:'Lopez', email:'patricio.pj.lopez2@bhpbilliton.com',  masterArea:'Production Port'},
    { firstName:'Carlos', secondName:'Alvarez', lastName:'Guillier', email:'carlos.ce.guillier@bhpbilliton.com',  masterArea:'Production Port'},
    { firstName:'Robinson', secondName:'Espinoza', lastName:'Campillay', email:'robinson.ra.campillay@bhpbilliton.com',  masterArea:'Production Port'},
    { firstName:'Jorge', secondName:'Dubo', lastName:'Rojo', email:'jorge.js.rojo@bhpbilliton.com',  masterArea:'Production Port'},
    { firstName:'Isaias', secondName:'Irribarra', lastName:'Avalos', email:'isaias.ia.avalos@bhpbilliton.com',  masterArea:'Production Port'},
    { firstName:'Pablo', secondName:'Araya', lastName:'Chavez', email:'pablo.pa.chavez@bhpbilliton.com',  masterArea:'Production Port'},
    { firstName:'Luis', secondName:'Soza', lastName:'Arroyo', email:'luis.a.arroyo@bhpbilliton.com',  masterArea:'Production Port'},
    { firstName:'Hector', secondName:'Cortes', lastName:'Rojas', email:'hector.hf.rojas@bhpbilliton.com',  masterArea:'Production Port'},
    { firstName:'Arnoldo', secondName:'Rodriguez', lastName:'Correa', email:'arnoldo.af.correa@bhpbilliton.com',  masterArea:'Production Port'},
    { firstName:'Guillermo', secondName:'Leon', lastName:'Zapata', email:'guillermo.ga.zapata@bhpbilliton.com',  masterArea:'Production Port'},
    { firstName:'Ricardo', secondName:'Campos', lastName:'Lopez', email:'ricardo.a.lopez@bhpbilliton.com',  masterArea:'Production Port'},
    { firstName:'Sergio', secondName:'Mondaca', lastName:'Romero', email:'sergio.o.romero@bhpbilliton.com',  masterArea:'Production Port'},
    { firstName:'Sergio', secondName:'Rojas', lastName:'Lopez', email:'sergio.e.lopez@bhpbilliton.com',  masterArea:'Production Port'},
    { firstName:'Flavia', secondName:'Garrido', lastName:'Rojas', email:'flavia.fx.rojas@bhpbilliton.com',  masterArea:'Production Pipeline & Filter'},
    { firstName:'Mauricio', secondName:'Toledo', lastName:'Rodriguez', email:'mauricio.me.rodriguez@bhpbilliton.com',  masterArea:'Water Supply'},
    { firstName:'Javier', secondName:'Marco', lastName:'Fernandez', email:'javier.i.fernandez@bhpbilliton.com',  masterArea:'Production Port'},
    { firstName:'Marco', secondName:'Olivares', lastName:'Rodriguez', email:'marco.ma.rodriguez2@bhpbilliton.com',  masterArea:'Maintenance Power'},
    { firstName:'Luis', secondName:'Castillo', lastName:'Chivano', email:'luis.lr.chivano@bhpbilliton.com',  masterArea:'Maintenance Power'},
    { firstName:'Eduardo', secondName:'Acevedo', lastName:'Valenzuela', email:'eduardo.eh.valenzuela@bhpbilliton.com',  masterArea:'Maintenance Execution CHO'},
    { firstName:'Ricardo', secondName:'Castillo', lastName:'Cortes', email:'ricardo.rm.cortes@bhpbilliton.com',  masterArea:'Ingenieria'},
    { firstName:'Boris', secondName:'Velasquez', lastName:'Gatica', email:'boris.bp.gatica@bhpbilliton.com',  masterArea:'Maintenance Overhead Cranes'},
    { firstName:'Mario', secondName:'Martinez', lastName:'Ferrera', email:'mario.g.ferrera2@bhpbilliton.com',  masterArea:'Management Comissioning'},
    { firstName:'Nancy', secondName:'Miric', lastName:'Luza', email:'nancy.na.luza@bhpbilliton.com',  masterArea:'Water Supply'},
    { firstName:'Mariela', secondName:'Cartes', lastName:'Roa', email:'mariela.mf.roa@bhpbilliton.com',  masterArea:'Water Supply'},
    { firstName:'Oscar', secondName:'Torres', lastName:'Aranela', email:'oscar.om.aranela@bhpbilliton.com',  masterArea:'Maintenance Water'},
    { firstName:'Boris', secondName:'Rodriguez', lastName:'Gutierrez', email:'boris.bj.gutierrez@bhpbilliton.com',  masterArea:'Maintenance Water'},
    { firstName:'Gaston', secondName:'Marin', lastName:'Nuñez', email:'gaston.d.nunez@bhpbilliton.com',  masterArea:'Production Pipeline & Filter'},
    { firstName:'Carmen', secondName:'Carreño', lastName:'Salinas', email:'carmengloria.salinas@bhpbilliton.com',  masterArea:'Directo'},
    { firstName:'Luis', secondName:'Ceruti', lastName:'Gomez', email:'luis.gomez1@bhpbilliton.com',  masterArea:'Wells Field & Tailings Dam'},
    { firstName:'Jorge', secondName:'Pizarro', lastName:'Flores', email:'jorge.jl.flores@bhpbilliton.com',  masterArea:'Personnel Serv Contract Management'},
    { firstName:'Pablo', secondName:'Riquelme', lastName:'Castro', email:'pablo.pa.castro@bhpbilliton.com',  masterArea:'Maintenance Execution CHO'},
    { firstName:'Joel', secondName:'Valencia', lastName:'Castillo', email:'joel.ja.castillo@bhpbilliton.com',  masterArea:'Maintenance Overhead Cranes'},
    { firstName:'Sergio', secondName:'Cuellar', lastName:'Ruiz', email:'sergio.sr.ruiz@bhpbilliton.com',  masterArea:'Maintenance Planning NPI'},
    { firstName:'Felindo', secondName:'Henriquez', lastName:'Concha', email:'felindo.concha@bhpbilliton.com',  masterArea:'Maintenance Power'},
    { firstName:'Mauricio', secondName:'Pacheco', lastName:'Vasquez', email:'mauricio.ma.vasquez@bhpbilliton.com',  masterArea:'Maintenance Water'},
    { firstName:'Valeria', secondName:'Bustamante', lastName:'Fuentes', email:'valeria.fuentes@bhpbilliton.com',  masterArea:'Ingenieria'},
    { firstName:'Maria', secondName:'Rovegno', lastName:'Lampert', email:'mariaconstanza.lampert@bhpbilliton.com',  masterArea:'Personnel Services'},
    { firstName:'Maximiliano', secondName:'Agurto', lastName:'Platoni', email:'maximiliano.a.platoni@bhpbilliton.com',  masterArea:'Planning CHO'},
    { firstName:'Jessica', secondName:'Rodriguez', lastName:'Poblete', email:'jessica.poblete@bhpbilliton.com',  masterArea:'Power Supply'},
    { firstName:'Juan', secondName:'Sepulveda', lastName:'Molina', email:'juan.jp.molina@bhpbilliton.com',  masterArea:'Production Contract Management NPI'},
    { firstName:'Julio', secondName:'Fuentes', lastName:'Martinez', email:'julio.i.martinez@bhpbilliton.com',  masterArea:'Lifting Operations'},
    { firstName:'Miguel', secondName:'Salgado', lastName:'Molina', email:'miguel.s.molina@bhpbilliton.com',  masterArea:'Production Pipeline & Filter'},
    { firstName:'Andres', secondName:'Carmona', lastName:'Naranjo', email:'andres.aa.naranjo@bhpbilliton.com',  masterArea:'Prod. Planning'},
    { firstName:'Felipe', secondName:'Horta', lastName:'Jullian', email:'felipe.jullian@bhpbilliton.com',  masterArea:'Water Supply'},
    { firstName:'Rodrigo', secondName:'Bocic', lastName:'Ortiz', email:'rodrigo.re.ortiz@bhpbilliton.com',  masterArea:'Wells Field & Tailings Dam'},
    { firstName:'Francisco', secondName:'Potenza', lastName:'Aranda', email:'francisco.fm.aranda@bhpbilliton.com',  masterArea:'Maintenance Power'},
    { firstName:'Juan', secondName:'Meneses', lastName:'Peñailillo', email:'juan.je.penailillo@bhpbilliton.com',  masterArea:'Maintenance Power'},
    { firstName:'Monica', secondName:'Navea', lastName:'Gonzalez', email:'monica.mm.gonzalez@bhpbilliton.com',  masterArea:'Personnel Services'},
    { firstName:'Andrea', secondName:'Rokov', lastName:'Bustamante', email:'andrea.ap.bustamante@bhpbilliton.com',  masterArea:'Personnel Services'},
    { firstName:'Maurizio', secondName:'Manniello', lastName:'Squartini', email:'maurizio.mc.squartini@bhpbilliton.com',  masterArea:'Personnel Services'},
    { firstName:'Gino', secondName:'Sepulveda', lastName:'Varela', email:'gino.ga.varela@bhpbilliton.com',  masterArea:'Personnel Services'},
    { firstName:'Jose', secondName:'Morales', lastName:'Tapia', email:'jose.ja.tapia@bhpbilliton.com',  masterArea:'Personnel Services'},
    { firstName:'Marcelo', secondName:'Cortes', lastName:'Esquivel', email:'marcelo.ma.esquivel@bhpbilliton.com',  masterArea:'Services Antofagasta'},
    { firstName:'Silvano', secondName:'Cofre', lastName:'Martinez', email:'silvano.sm.martinez@bhpbilliton.com',  masterArea:'A&I CHO'},
    { firstName:'Patricio', secondName:'Arevalo', lastName:'Torres', email:'patricio.po.torres@bhpbilliton.com',  masterArea:'A&I NPI'},
    { firstName:'Rodrigo', secondName:'Sotomayor', lastName:'Diaz', email:'rodrigo.diaz1@bhpbilliton.com',  masterArea:'Production Port'},
    { firstName:'Felipe', secondName:'Diaz', lastName:'Duery', email:'felipe.f.duery@bhpbilliton.com',  masterArea:'Management Comissioning'},
    { firstName:'Jose', secondName:'Carreño', lastName:'Cavieres', email:'jose.d.cavieres@bhpbilliton.com',  masterArea:'Production Contract Management NPI'},
    { firstName:'Bernardo', secondName:'Marin', lastName:'Fuentes', email:'bernardo.a.fuentes@bhpbilliton.com',  masterArea:'Water Supply'},
    { firstName:'Yslen', secondName:'Gonzalez', lastName:'Yaksic', email:'yslen.yaksic@bhpbilliton.com',  masterArea:'Water Supply'},
    { firstName:'Danitza', secondName:'Sanchez', lastName:'Perez', email:'danitza.perez@bhpbilliton.com',  masterArea:'Water Supply'},
    { firstName:'Claudia', secondName:'Pino', lastName:'Del Canto', email:'claudia.delcanto@bhpbilliton.com',  masterArea:'Water Supply'},
    { firstName:'Roberto', secondName:'Palma', lastName:'Silva', email:'roberto.ra.silva@bhpbilliton.com',  masterArea:'Maintenance Water'},
    { firstName:'Julio', secondName:'Jofre', lastName:'Lemus', email:'julio.jc.lemus@bhpbilliton.com',  masterArea:'Maintenance Water'},
    { firstName:'Cristian', secondName:'Contreras', lastName:'Trujillo', email:'cristian.co.trujillo@bhpbilliton.com',  masterArea:'Maintenance Execution CHO'},
    { firstName:'Juan', secondName:'Etchebaster', lastName:'Alfaro', email:'juan.m.alfaro@bhpbilliton.com',  masterArea:'Maintenance Execution CHO'},
    { firstName:'Edgardo', secondName:'Aguirre', lastName:'Berrios', email:'edgardo.ej.berrios@bhpbilliton.com',  masterArea:'Maintenance Execution CHO'},
    { firstName:'Alejandro', secondName:'Jeldres', lastName:'Henriquez', email:'alejandro.ah.henriquez@bhpbilliton.com',  masterArea:'Maintenance Water'},
    { firstName:'Luis', secondName:'Moral', lastName:'Canales', email:'luis.le.canales@bhpbilliton.com',  masterArea:'Maintenance Water'},
    { firstName:'Javier', secondName:'Cañas', lastName:'Dougnac', email:'javier.ja.dougnac@bhpbilliton.com',  masterArea:'Maintenance Water'},
    { firstName:'Roberto', secondName:'Sanchez', lastName:'Carvajal', email:'roberto.ra.carvajal@bhpbilliton.com',  masterArea:'Maintenance Execution CHO'},
    { firstName:'Diego', secondName:'Kalasic', lastName:'Gonzalez', email:'diego.dh.gonzalez@bhpbilliton.com',  masterArea:'Maintenance Power'},
    { firstName:'Gabriel', secondName:'Lazcano', lastName:'Lopez', email:'gabriel.gl.lopez@bhpbilliton.com',  masterArea:'Maintenance Power'},
    { firstName:'Jose', secondName:'Caimanque', lastName:'Marquez', email:'jose.jm.marquez@bhpbilliton.com',  masterArea:'Maintenance Overhead Cranes'},
    { firstName:'Francisco', secondName:'Bernal', lastName:'Barrientos', email:'francisco.fj.barrientos@bhpbilliton.com',  masterArea:'Maintenance Overhead Cranes'},
    { firstName:'Gilberto', secondName:'Faundez', lastName:'Chandia', email:'gilberto.ga.chandia@bhpbilliton.com',  masterArea:'Maintenance Overhead Cranes'},
    { firstName:'Juan', secondName:'Fredes', lastName:'Salinas', email:'juan.jp.salinas@bhpbilliton.com',  masterArea:'Maintenance Overhead Cranes'},
    { firstName:'Anelis', secondName:'Leiva', lastName:'Quintero', email:'anelis.quintero@bhpbilliton.com',  masterArea:'Maintenance Overhead Cranes'},
    { firstName:'Rodrigo', secondName:'Quezada', lastName:'Luengo', email:'rodrigo.rl.luengo@bhpbilliton.com',  masterArea:'Maintenance Water'},
    { firstName:'Ernesto', secondName:'Campos', lastName:'Lopez', email:'ernesto.ea.lopez@bhpbilliton.com',  masterArea:'Maintenance Execution CHO'},
    { firstName:'Patricio', secondName:'Paz', lastName:'Farias', email:'patricio.farias@bhpbilliton.com',  masterArea:'Maintenance Water'},
    { firstName:'Enrique', secondName:'Toro', lastName:'Berrios', email:'enrique.ef.berrios@bhpbilliton.com',  masterArea:'Maintenance Execution CHO'},
    { firstName:'Jose', secondName:'Ape', lastName:'Osorio', email:'jose.jl.osorio@bhpbilliton.com',  masterArea:'Maintenance Execution CHO'},
    { firstName:'Patricio', secondName:'Barrios', lastName:'Robles', email:'patricio.p.robles@bhpbilliton.com',  masterArea:'Maintenance Execution CHO'},
    { firstName:'Pedro', secondName:'Cabrera', lastName:'Toledo', email:'pedro.pd.toledo@bhpbilliton.com',  masterArea:'Maintenance Execution CHO'},
    { firstName:'Marco', secondName:'Castillo', lastName:'Vera', email:'marco.ma.vera@bhpbilliton.com',  masterArea:'Maintenance Water'},
    { firstName:'Guido', secondName:'Gutierrez', lastName:'Cabrera', email:'guido.gd.cabrera@bhpbilliton.com',  masterArea:'Maintenance Water'},
    { firstName:'Rodrigo', secondName:'Quiroga', lastName:'Paredes', email:'rodrigo.ra.paredes@bhpbilliton.com',  masterArea:'Maintenance Water'},
    { firstName:'Pedro', secondName:'Brunacci', lastName:'Sierra', email:'pedro.pf.sierra@bhpbilliton.com',  masterArea:'Maintenance Water'},
    { firstName:'Michel', secondName:'Ponce', lastName:'Loyer', email:'michel.ma.loyer@bhpbilliton.com',  masterArea:'Maintenance Water'},
    { firstName:'Juan', secondName:'Collao', lastName:'Espindola', email:'juan.c.espindola@bhpbilliton.com',  masterArea:'Lifting Operations'},
    { firstName:'Victor', secondName:'Jorquera', lastName:'Araya', email:'victor.vh.araya1@bhpbilliton.com',  masterArea:'Lifting Operations'},
    { firstName:'Jorge', secondName:'Hernandez', lastName:'Ibañez', email:'jorge.jl.ibanez@bhpbilliton.com',  masterArea:'Lifting Operations'},
    { firstName:'Edison', secondName:'Espejo', lastName:'Roa', email:'edison.ea.roa@bhpbilliton.com',  masterArea:'Lifting Operations'},
    { firstName:'Eduardo', secondName:'Aguila', lastName:'Aravena', email:'eduardo.e.aravena@bhpbilliton.com',  masterArea:'Water Supply'},
    { firstName:'Sergio', secondName:'Rojas', lastName:'Geraldo', email:'sergio.sl.geraldo@bhpbilliton.com',  masterArea:'Water Supply'},
    { firstName:'Christian', secondName:'Vergara', lastName:'Herrera', email:'christian.cm.herrera@bhpbilliton.com',  masterArea:'Water Supply'},
    { firstName:'Ricardo', secondName:'Vecchiola', lastName:'Marin', email:'ricardo.a.marin@bhpbilliton.com',  masterArea:'Water Supply'},
    { firstName:'Macarena', secondName:'Nuñez', lastName:'Arellano', email:'macarena.mp.arellano@bhpbilliton.com',  masterArea:'Water Supply'},
    { firstName:'Elba', secondName:'Barreda', lastName:'Pinto', email:'elba.pinto@bhpbilliton.com',  masterArea:'Water Supply'},
    { firstName:'Mauricio', secondName:'Milla', lastName:'Becerra', email:'mauricio.ma.becerra@bhpbilliton.com',  masterArea:'Wells Field & Tailings Dam'},
    { firstName:'Mauricio', secondName:'Gutierrez', lastName:'Bravo', email:'mauricio.me.bravo@bhpbilliton.com',  masterArea:'Wells Field & Tailings Dam'},
    { firstName:'Manuel', secondName:'Peralta', lastName:'Gallegos', email:'manuel.mj.gallegos@bhpbilliton.com',  masterArea:'Wells Field & Tailings Dam'},
    { firstName:'Domingo', secondName:'Basaure', lastName:'Espinoza', email:'domingo.ds.espinoza@bhpbilliton.com',  masterArea:'Wells Field & Tailings Dam'},
    { firstName:'Franco', secondName:'Torres', lastName:'Hermosilla', email:'franco.ha.hermosilla@bhpbilliton.com',  masterArea:'Wells Field & Tailings Dam'},
    { firstName:'Gustavo', secondName:'Araya', lastName:'Aguirre', email:'gustavo.u.aguirre@bhpbilliton.com',  masterArea:'Production Pipeline & Filter'},
    { firstName:'Hugo', secondName:'Lopez', lastName:'Montaña', email:'hugo.p.montana@bhpbilliton.com',  masterArea:'Production Pipeline & Filter'},
    { firstName:'Juan', secondName:'Vasquez', lastName:'Tapia', email:'juan.a.tapia@bhpbilliton.com',  masterArea:'Production Pipeline & Filter'},
    { firstName:'Luis', secondName:'Vargas', lastName:'Cortes', email:'luis.ld.cortes@bhpbilliton.com',  masterArea:'Production Pipeline & Filter'},
    { firstName:'Marcela', secondName:'Poblete', lastName:'Fuentealba', email:'marcela.mf.fuentealba@bhpbilliton.com',  masterArea:'Production Port'},
    { firstName:'Arnaldo', secondName:'Zapata', lastName:'Ortega', email:'arnaldo.as.ortega@bhpbilliton.com',  masterArea:'Production Port'},
    { firstName:'Arsenio', secondName:'Escudero', lastName:'Aguilera', email:'arsenio.m.aguilera@bhpbilliton.com',  masterArea:'Production Port'},
    { firstName:'Gino', secondName:'Galleguillos', lastName:'Villalobos', email:'gino.gl.villalobos@bhpbilliton.com',  masterArea:'Production Port'},
    { firstName:'Marco', secondName:'Paez', lastName:'Nuñez', email:'marco.ma.nunez@bhpbilliton.com',  masterArea:'Production Pipeline & Filter'},
    { firstName:'Maria', secondName:'Cañete', lastName:'Quijanes', email:'maria.quijanes@bhpbilliton.com',  masterArea:'Production Pipeline & Filter'},
    { firstName:'Patricio', secondName:'Olivares', lastName:'Olivares', email:'patricio.pa.olivares@bhpbilliton.com',  masterArea:'Production Pipeline & Filter'},
    { firstName:'Ramon', secondName:'Badilla', lastName:'Leiva', email:'ramon.re.leiva@bhpbilliton.com',  masterArea:'Production Pipeline & Filter'},
    { firstName:'Sergio', secondName:'Campos', lastName:'Galleguillos', email:'sergio.sb.galleguillos@bhpbilliton.com',  masterArea:'Production Pipeline & Filter'},
    { firstName:'Alfonso', secondName:'Salas', lastName:'Arratia', email:'alfonso.arratia@bhpbilliton.com',  masterArea:'Wells Field & Tailings Dam'},
    { firstName:'Nivaldo', secondName:'Devia', lastName:'Vergara', email:'nivaldo.vergara@bhpbilliton.com',  masterArea:'Wells Field & Tailings Dam'},
    { firstName:'Constanza', secondName:'Egnem', lastName:'Zavala', email:'',  masterArea:'Wells Field & Tailings Dam'},
    { firstName:'Eduardo', secondName:'Tapia', lastName:'Castillo', email:'eduardo.j.castillo@bhpbilliton.com',  masterArea:'Wells Field & Tailings Dam'},
    { firstName:'Robertson', secondName:'Aros', lastName:'Muñoz', email:'robertson.p.munoz@bhpbilliton.com',  masterArea:'Wells Field & Tailings Dam'},
    { firstName:'Christian', secondName:'Contreras', lastName:'Castillo', email:'christian.o.castillo@bhpbilliton.com',  masterArea:'Wells Field & Tailings Dam'},
    { firstName:'Elias', secondName:'Caimanque', lastName:'Pizarro', email:'elias.ej.pizarro@bhpbilliton.com',  masterArea:'Wells Field & Tailings Dam'},
    { firstName:'Nelson', secondName:'Moyano', lastName:'Nuñez', email:'nelson.a.nunez@bhpbilliton.com',  masterArea:'Wells Field & Tailings Dam'},
    { firstName:'Luis', secondName:'Aguilera', lastName:'Zambra', email:'luis.a.zambra@bhpbilliton.com',  masterArea:'Wells Field & Tailings Dam'},
    { firstName:'Alex', secondName:'Pinto', lastName:'Catalan', email:'alex.m.catalan@bhpbilliton.com',  masterArea:'Wells Field & Tailings Dam'},
    { firstName:'Luis', secondName:'Olmos', lastName:'Breton', email:'luis.la.breton@bhpbilliton.com',  masterArea:'Wells Field & Tailings Dam'},
    { firstName:'Alberto', secondName:'Aliaz', lastName:'Barrera', email:'alberto.ae.barrera@bhpbilliton.com',  masterArea:'Wells Field & Tailings Dam'},
    { firstName:'Sigifredo', secondName:'Rios', lastName:'Olmedo', email:'sigisfredo.e.olmedo@bhpbilliton.com',  masterArea:'Wells Field & Tailings Dam'},
    { firstName:'Oliver', secondName:'Ponce', lastName:'Merino', email:'oliver.r.merino@bhpbilliton.com',  masterArea:'Wells Field & Tailings Dam'},
    { firstName:'Alexis', secondName:'Campos', lastName:'Alquinta', email:'alexis.af.alquinta@bhpbilliton.com',  masterArea:'Wells Field & Tailings Dam'},

]

export default personsData